name: testingbinder
channels:
 - anaconda
 - conda-forge
dependencies:
 - python
 - numpy
 - scipy
 - pandas
 - matplotlib
 - bokeh
 - pytest
 - ipytest
 - pip
 - pip:
   - binarytree
   - ipympl
   - git+https://github.com/MJTMace/callhorizons.git@get-vectors-feature-branch 
